version: '2'

volumes:
  grafana_data:

services:

 streamsexporter:
    image: "docker_streamsexporter:latest"
    env_file:
      - ./streamsexporter/prod.env
    ports:
      - 25500:25500
#   environment:
#     - STREAMS_DOMAIN_ID


  prometheus:
    image: "dockerproxy-iva.si.francetelecom.fr/prom/prometheus:latest"
    volumes:
      - ./prometheus/prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    depends_on:
      - prometheus
    image: "dockerproxy-iva.si.francetelecom.fr/grafana/grafana:latest"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
     - 3000:3000
